data_dir: "D:/Audion-Data/Urdu"
output_dir: "outputs/urdu"

sample_rate: 16000
silence_thresh_db: -40.0
min_silence_ms: 400
target_max_ms: 30000
floor_ms: 2000

whisper_model: "base"
device: "cuda"
language: "ur"

dataset_version: "v2-day1"

sources:
  - id: podcast1
    filename: "Urdu-Podcast1-Male-Neutral.mp3"
  - id: podcast2
    filename: "Urdu-Podcast2-maleAndFemal-Neutral.mp3"
  - id: podcast3
    filename: "Urdu-Podcast3-Male-Neutral.mpeg"
